--- 
networks: 
  envoymesh: {}
services: 
  front-envoy: 
    build: 
      context: apps
      dockerfile: Dockerfile-frontenvoy
    expose: 
      - "80"
      - "8001"
    networks: 
      - envoymesh
    ports: 
      - "8000:80"
      - "8001:8001"
    volumes: 
      - "./front-envoy.yaml:/etc/front-envoy.yaml"
  grafana: 
    image: grafana/grafana
    networks: 
      envoymesh: 
        aliases: 
          - grafana
    ports: 
      - "3000:3000"
    volumes: 
      - "./config/grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml"
      - "./config/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml"
      - "./config/grafana/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json"
  jaeger: 
    environment: 
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    expose: 
      - "9411"
      - "16686"
    image: jaegertracing/all-in-one
    networks: 
      envoymesh: 
        aliases: 
          - jaeger
    ports: 
      - "9411:9411"
      - "16686:16686"
  prometheus: 
    command: "--config.file=/etc/prometheus.yaml"
    image: prom/prometheus
    networks: 
      envoymesh: 
        aliases: 
          - prometheus
    ports: 
      - "9090:9090"
    volumes: 
      - "./config/prometheus/config.yaml:/etc/prometheus.yaml"
  service_a: 
    build: 
      context: apps
      dockerfile: Dockerfile-service
    environment: 
      - SERVICE_NAME=a
    expose: 
      - "80"
    networks: 
      envoymesh: 
        aliases: 
          - service_a
    volumes: 
      - "./service-a-envoy.yaml:/etc/service-a-envoy.yaml"
  service_b: 
    build: 
      context: apps
      dockerfile: Dockerfile-service
    environment: 
      - SERVICE_NAME=b
    expose: 
      - "80"
    networks: 
      envoymesh: 
        aliases: 
          - service_b
    volumes: 
      - "./service-b-envoy.yaml:/etc/service-b-envoy.yaml"
  statsd_exporter: 
    image: "prom/statsd-exporter:latest"
    networks: 
      envoymesh: 
        aliases: 
          - statsd
    ports: 
      - "9125:9125"
      - "9102:9102"
version: "2"
