FROM envoyproxy/envoy:latest
RUN apt-get update && apt-get -q install -y curl
CMD /usr/local/bin/envoy -c /etc/front-envoy.yaml -l info --service-cluster front-envoy --service-node front-envoy --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'